### ISSUE TITLE
Function to convert to svg path

### ISSUE THREAD

**Issue by jonnitto** [chdh/function-curve-editor#4]
Hi @chdh 

Thank you a lot for this editor, it was a huge inspiration. Do you know what the best method would be to convert a given graph to a svg path?

**Comment by chdh** [comment]
No, I don't know a good method to generate SVG from the function curve.

One approach could be to programmatically generate an SVG path from the interpolated curve, possibly using small Bézier or elliptical SVG curve segments. Or many small straight line segments.

Another approach could be to just use the knots and perform the interpolation entirely with SVG Bezier.
See example [here](https://stackoverflow.com/a/64934180/337221) for calculating the Bezier control points.

**Comment by jonnitto** [comment]
@chdh Thank you for your answer. I'll will try this approach. I close this issue, as it is not a bug or something similar

**Comment by jonnitto** [comment]
I made quite a good progress… 

<img width="2110" alt="image" src="https://github.com/user-attachments/assets/a0dd185a-eb6d-4862-95cd-7fe49ca03276">

This is an editor for [Neos](https://neos.io) where you can edit some visual stuff on elements
